
package br.com.paulo.cotacaows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CotacaoMoedaWS", targetNamespace = "http://cotacaoWS.paulo.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CotacaoMoedaWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotacao", targetNamespace = "http://cotacaoWS.paulo.com.br/", className = "br.com.paulo.cotacaows.Cotacao")
    @ResponseWrapper(localName = "cotacaoResponse", targetNamespace = "http://cotacaoWS.paulo.com.br/", className = "br.com.paulo.cotacaows.CotacaoResponse")
    public double cotacao(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
