
package br.com.paulo.cotacaows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CotacaoMoedaWSService", targetNamespace = "http://cotacaoWS.paulo.com.br/", wsdlLocation = "http://localhost:8080/ProjetoWSAeroPorto/CotacaoMoedaWS?wsdl")
public class CotacaoMoedaWSService
    extends Service
{

    private final static URL COTACAOMOEDAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COTACAOMOEDAWSSERVICE_EXCEPTION;
    private final static QName COTACAOMOEDAWSSERVICE_QNAME = new QName("http://cotacaoWS.paulo.com.br/", "CotacaoMoedaWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProjetoWSAeroPorto/CotacaoMoedaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COTACAOMOEDAWSSERVICE_WSDL_LOCATION = url;
        COTACAOMOEDAWSSERVICE_EXCEPTION = e;
    }

    public CotacaoMoedaWSService() {
        super(__getWsdlLocation(), COTACAOMOEDAWSSERVICE_QNAME);
    }

    public CotacaoMoedaWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COTACAOMOEDAWSSERVICE_QNAME, features);
    }

    public CotacaoMoedaWSService(URL wsdlLocation) {
        super(wsdlLocation, COTACAOMOEDAWSSERVICE_QNAME);
    }

    public CotacaoMoedaWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COTACAOMOEDAWSSERVICE_QNAME, features);
    }

    public CotacaoMoedaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CotacaoMoedaWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CotacaoMoedaWS
     */
    @WebEndpoint(name = "CotacaoMoedaWSPort")
    public CotacaoMoedaWS getCotacaoMoedaWSPort() {
        return super.getPort(new QName("http://cotacaoWS.paulo.com.br/", "CotacaoMoedaWSPort"), CotacaoMoedaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CotacaoMoedaWS
     */
    @WebEndpoint(name = "CotacaoMoedaWSPort")
    public CotacaoMoedaWS getCotacaoMoedaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cotacaoWS.paulo.com.br/", "CotacaoMoedaWSPort"), CotacaoMoedaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COTACAOMOEDAWSSERVICE_EXCEPTION!= null) {
            throw COTACAOMOEDAWSSERVICE_EXCEPTION;
        }
        return COTACAOMOEDAWSSERVICE_WSDL_LOCATION;
    }

}
