
package br.com.paulo.distanciaws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DistanciaWSService", targetNamespace = "http://distanciaWS.paulo.com.br/", wsdlLocation = "http://localhost:8080/ProjetoWSAeroPorto/DistanciaWS?wsdl")
public class DistanciaWSService
    extends Service
{

    private final static URL DISTANCIAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISTANCIAWSSERVICE_EXCEPTION;
    private final static QName DISTANCIAWSSERVICE_QNAME = new QName("http://distanciaWS.paulo.com.br/", "DistanciaWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProjetoWSAeroPorto/DistanciaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISTANCIAWSSERVICE_WSDL_LOCATION = url;
        DISTANCIAWSSERVICE_EXCEPTION = e;
    }

    public DistanciaWSService() {
        super(__getWsdlLocation(), DISTANCIAWSSERVICE_QNAME);
    }

    public DistanciaWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISTANCIAWSSERVICE_QNAME, features);
    }

    public DistanciaWSService(URL wsdlLocation) {
        super(wsdlLocation, DISTANCIAWSSERVICE_QNAME);
    }

    public DistanciaWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISTANCIAWSSERVICE_QNAME, features);
    }

    public DistanciaWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DistanciaWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DistanciaWS
     */
    @WebEndpoint(name = "DistanciaWSPort")
    public DistanciaWS getDistanciaWSPort() {
        return super.getPort(new QName("http://distanciaWS.paulo.com.br/", "DistanciaWSPort"), DistanciaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DistanciaWS
     */
    @WebEndpoint(name = "DistanciaWSPort")
    public DistanciaWS getDistanciaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://distanciaWS.paulo.com.br/", "DistanciaWSPort"), DistanciaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISTANCIAWSSERVICE_EXCEPTION!= null) {
            throw DISTANCIAWSSERVICE_EXCEPTION;
        }
        return DISTANCIAWSSERVICE_WSDL_LOCATION;
    }

}
