
package br.com.paulo.distanciaws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DistanciaWS", targetNamespace = "http://distanciaWS.paulo.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DistanciaWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculaDistancia", targetNamespace = "http://distanciaWS.paulo.com.br/", className = "br.com.paulo.distanciaws.CalculaDistancia")
    @ResponseWrapper(localName = "calculaDistanciaResponse", targetNamespace = "http://distanciaWS.paulo.com.br/", className = "br.com.paulo.distanciaws.CalculaDistanciaResponse")
    public double calculaDistancia(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
