
package br.com.paulo.validacaows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidaCPF_CNPJWSService", targetNamespace = "http://validacaoWS.paulo.com.br/", wsdlLocation = "http://localhost:8080/ProjetoWSAeroPorto/ValidaCPF_CNPJWS?wsdl")
public class ValidaCPFCNPJWSService
    extends Service
{

    private final static URL VALIDACPFCNPJWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDACPFCNPJWSSERVICE_EXCEPTION;
    private final static QName VALIDACPFCNPJWSSERVICE_QNAME = new QName("http://validacaoWS.paulo.com.br/", "ValidaCPF_CNPJWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProjetoWSAeroPorto/ValidaCPF_CNPJWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDACPFCNPJWSSERVICE_WSDL_LOCATION = url;
        VALIDACPFCNPJWSSERVICE_EXCEPTION = e;
    }

    public ValidaCPFCNPJWSService() {
        super(__getWsdlLocation(), VALIDACPFCNPJWSSERVICE_QNAME);
    }

    public ValidaCPFCNPJWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDACPFCNPJWSSERVICE_QNAME, features);
    }

    public ValidaCPFCNPJWSService(URL wsdlLocation) {
        super(wsdlLocation, VALIDACPFCNPJWSSERVICE_QNAME);
    }

    public ValidaCPFCNPJWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDACPFCNPJWSSERVICE_QNAME, features);
    }

    public ValidaCPFCNPJWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaCPFCNPJWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidaCPFCNPJWS
     */
    @WebEndpoint(name = "ValidaCPF_CNPJWSPort")
    public ValidaCPFCNPJWS getValidaCPFCNPJWSPort() {
        return super.getPort(new QName("http://validacaoWS.paulo.com.br/", "ValidaCPF_CNPJWSPort"), ValidaCPFCNPJWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaCPFCNPJWS
     */
    @WebEndpoint(name = "ValidaCPF_CNPJWSPort")
    public ValidaCPFCNPJWS getValidaCPFCNPJWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://validacaoWS.paulo.com.br/", "ValidaCPF_CNPJWSPort"), ValidaCPFCNPJWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDACPFCNPJWSSERVICE_EXCEPTION!= null) {
            throw VALIDACPFCNPJWSSERVICE_EXCEPTION;
        }
        return VALIDACPFCNPJWSSERVICE_WSDL_LOCATION;
    }

}
