
package br.com.paulo.estudosejbws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://estudosEJBWS.paulo.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculadora {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicacao", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.Multiplicacao")
    @ResponseWrapper(localName = "multiplicacaoResponse", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.MultiplicacaoResponse")
    public double multiplicacao(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divisap", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.Divisap")
    @ResponseWrapper(localName = "divisapResponse", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.DivisapResponse")
    public double divisap(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtracao", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.Subtracao")
    @ResponseWrapper(localName = "subtracaoResponse", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.SubtracaoResponse")
    public double subtracao(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soma", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.Soma")
    @ResponseWrapper(localName = "somaResponse", targetNamespace = "http://estudosEJBWS.paulo.com.br/", className = "br.com.paulo.estudosejbws.SomaResponse")
    public double soma(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
