
package br.com.paulo.estudosws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Random", targetNamespace = "http://estudosWS.paulo.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Random {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "next", targetNamespace = "http://estudosWS.paulo.com.br/", className = "br.com.paulo.estudosws.Next")
    @ResponseWrapper(localName = "nextResponse", targetNamespace = "http://estudosWS.paulo.com.br/", className = "br.com.paulo.estudosws.NextResponse")
    @Action(input = "http://estudosWS.paulo.com.br/Random/nextRequest", output = "http://estudosWS.paulo.com.br/Random/nextResponse")
    public double next(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
