
package br.com.paulo.precogasws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrecoGasolinaWS", targetNamespace = "http://precoGasWS.paulo.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrecoGasolinaWS {


    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "precoGasolina", targetNamespace = "http://precoGasWS.paulo.com.br/", className = "br.com.paulo.precogasws.PrecoGasolina")
    @ResponseWrapper(localName = "precoGasolinaResponse", targetNamespace = "http://precoGasWS.paulo.com.br/", className = "br.com.paulo.precogasws.PrecoGasolinaResponse")
    public float precoGasolina();

}
